#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include "malloc.h"
#include "tst.h"
#include "brk.h"

#define MINSIZE 1
#define MAXSIZE 4096
#define ITERS 4096

#define SMALL 's'
#define LARGE 'l'
#define RANDOM 'r'
#define INCREASING 'i'
#define DECREASING 'd'

int main(int argc, char *argv[])
{
    char type = RANDOM;
    if (argc > 1)
        type = argv[1][0];

    srand(7); //Seed with a random number generated by a dice roll
    void *start, *end;

#ifdef MMAP
  start = endHeap();
#else
  start = (void *)sbrk(0);
#endif

    double *pointers[ITERS];
    int mem_size = MINSIZE;
    switch (type) {
    case INCREASING:
        mem_size = MINSIZE;
        break;
    case DECREASING:
        mem_size = MAXSIZE;
        break;
    default:
        break;
    }
    long allocated_memory = 0;
    int i = 0;
    for (i = 0; i < ITERS; i++) {
        switch (type) {
        case SMALL:
            mem_size = MINSIZE;
            break;
        case LARGE:
            mem_size = MAXSIZE;
            break;
        case RANDOM:
            mem_size = rand() % MAXSIZE;
            break;
        case INCREASING:
            if (mem_size < MAXSIZE)
                mem_size++;
            break;
        case DECREASING:
            if (mem_size > MINSIZE)
                mem_size--;
            break;
        default:
            break;
        }
        int size = mem_size*sizeof(double);
        pointers[i] = (double *) malloc(size);
        allocated_memory += size;
    }

    for (i = 0; i < ITERS; i++) {
        free(pointers[i]);
    }

#ifdef MMAP
    end = endHeap();
#else
    end = (void *) sbrk(0);
#endif

    unsigned long used_memory = (unsigned long) (end - start);
    printf("Memory used by program: %ld\n", used_memory);
    printf("Allocated memory: %ld\n", allocated_memory);
    return 0;
}


