#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include "malloc.h"
#include "tst.h"
#include "brk.h"
#include <sys/time.h>

#define MINSIZE 1
#define MAXSIZE 4096
#define WORSTSIZE 512
#define BESTSIZE 511
#define ITERS 4096

/* define different test cases */
#define SMALL 's'
#define LARGE 'l'
#define RANDOM 'r'
#define INCREASING 'i'
#define DECREASING 'd'
#define BEST 'b'
#define WORST 'w'

typedef long Align;             /* for alignment to long boundary */

union header {                  /* block header */
    struct {
        union header *ptr;      /* next block if on free list */
        unsigned size;          /* size of this block  - what unit? */ 
    } s;
    Align x;                    /* force alignment of blocks */
};

typedef union header Header;

int main(int argc, char *argv[])
{
    struct timeval starttime, endtime; /* start- and end-time  */
    gettimeofday(&starttime, NULL);

    char type = RANDOM;
    if (argc > 1)
        type = argv[1][0];

    srand(7); //Seed with a random number generated by a dice roll
    void *start, *end;

#if STRATEGY != 0
  start = endHeap();
#else
  start = (void *)sbrk(0);
#endif

    Header *pointers[ITERS];
    int mem_size = MINSIZE; /* start on MINSIZE */
    switch (type) {
    case INCREASING:
        mem_size = MINSIZE; /* start on MINSIZE */
        break;
    case DECREASING:
        mem_size = MAXSIZE; /* start on MAXSIZE */
        break;
    default:
        break;
    }
    long allocated_memory = 0;
    int i = 0;
    for (i = 0; i < ITERS; i++) {
        switch (type) {
        case SMALL:
            mem_size = MINSIZE; /* always MINSIZE */
            break;
        case LARGE:
            mem_size = MAXSIZE; /* always MAXSIZE */
            break;
        case RANDOM:
            mem_size = rand() % MAXSIZE; /* Random size between 0 and MAXSIZE */
            break;
        case INCREASING:
            if (mem_size < MAXSIZE) /* Increase by 1 every round */
                mem_size++;
            break;
        case DECREASING:
            if (mem_size > MINSIZE)
                mem_size--; /* decrease by 1 every round */
            break;
        case BEST:
            mem_size = BESTSIZE; /* always same size */
            break;
        case WORST:
            mem_size = WORSTSIZE; /* always same size */
            break;
        default:
            break;
        }
        int size = mem_size*sizeof(Header); /* allocate x number of Headers */
        pointers[i] = (Header *) malloc(size);
        allocated_memory += size; /* count how much memory has been allocated */
    }

/* check used memory */
#if STRATEGY != 0
    end = endHeap();
#else
    end = (void *) sbrk(0);
#endif

    for (i = 0; i < ITERS; i++) { /* free the memory again */
        free(pointers[i]);
    }

    gettimeofday(&endtime, NULL); /* get current time */
    long runtime = (long) (endtime.tv_sec - starttime.tv_sec) * 1000; /* runtime is endtime - starttime */
    runtime += (long) (endtime.tv_usec - starttime.tv_usec) / 1000; /* microsecond */
    printf("Time: %ldms\n", runtime);

    unsigned long used_memory = (unsigned long) (end - start);
    printf("Memory used by program: %ld\n", used_memory);
    printf("Allocated memory: %ld\n", allocated_memory);
    double efficiancy = (double) allocated_memory / used_memory;
    printf("Allocation efficiancy: %f\n", efficiancy);
    return 0;
}


